### ISSUE TITLE
ReferenceError: Ajax is not defined

### ISSUE THREAD

**Issue by Andyt8** [joshp23/tt-rss-yourls#12]
Hello, with the latest version of Tiny Tiny RSS (21.03) it stopped working. I updated from an older version sometimes from 2020. Therefore, maybe it already occur longer.

If I want to set up the settings, I see after using "save" button the error:
anonymous@https://domain/tt-rss/lib/dojo/tt-rss-layer.js?1615300183 line 8 > Function:7:7
_onSubmit@https://domain/tt-rss/lib/dojo/tt-rss-layer.js?1615300183:8:238947
hitch/<@https://domain/tt-rss/lib/dojo/dojo.js?1615300183:8:94550
__onClick@https://domain/tt-rss/lib/dojo/tt-rss-layer.js?1615300183:8:335911
hitch/<@https://domain/tt-rss/lib/dojo/dojo.js?1615300183:8:94550

At the moment, I don't know how to invest that or to fix that.

**Comment by Andyt8** [comment]
There was a really good overlap.... - I found after sending my issue your release post with new version. Before it didn't see that, because of older cache / website information. Will try it and close the issue if it work.

**Comment by Andyt8** [comment]
Hello, I did an update to 2.00 and the problem is still there. If I want to add my base URL and API Key, I see an error message with the title "ReferenceError: Ajax is not defined" and at Stack trace the above message.

I use Tiny Tiny RSS 21.03 with PostgreSQL. Don't know if that make a different - before I used with MariaDB/MySQL.

**Comment by joshp23** [comment]
fixed with latest 2.0.1

**Comment by Andyt8** [comment]
Thank you.
