### ISSUE TITLE
No https support?

### ISSUE THREAD

**Issue by Gabbalo** [joshp23/tt-rss-yourls#5]
Hi (again :D ) 

I gave the Plugin for the full address http**s**://short.domain.tld as option. 
the tt-rss instance is running under https as well.
However, the generated yourls link (which works!) starts with http://

Can this be fixed, so the complete address given in the options will be used for short-url generation?

Greets, Gabba

**Comment by Gabbalo** [comment]
The database contains the correct value (https://...) in table plugin_storage, so it must be altered somewhere between the SQL request and the integration in this plugin.

**Comment by joshp23** [comment]
I have been updating this, and in my installation the returned short url is `https://sho.rt`. This issue must be environment specific.
