### ISSUE TITLE
open_basedir and CURL with error messages

### ISSUE THREAD

**Issue by Andyt8** [joshp23/tt-rss-yourls#9]
Hello,

Is it possible to get an version without CURL? I don't know really much about CURL, but I know that my Webspace have open_basedir restrictions. Yes, that is not my own webserver - there are several points why it is in that way. However, if I want to use that plugin, I get really much Warnings and that fill up the error log.

I tried to add "//" for example to line 11 for testing => "// curl_setopt($this->curl_yourls, CURLOPT_FOLLOWLOCATION, true);" - plugin still work, but I don't know what that mean? The Warning will be reduced, but there are still some more with other lines - so is it safe to disable all?

I know, a good way would be to use "if (!ini_get('safe_mode') && !ini_get('open_basedir')) {"

**Comment by joshp23** [comment]
> Is it possible to get an version without CURL?  

Sorry, no.
> I don't know really much about CURL

[Here's](https://curl.haxx.se/) a good place to start

> so is it safe to disable all?

Safe? I would say it is not functional. Safe is another issue.
